version: 0.0
os: linux
files:
  - source: source
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 180
      runas: ubuntu